In [4]:
import numpy as np
scores = [89,56.34,76,89,98]
first_arr = np.array(scores)
print(first_arr)
print(first_arr.dtype)


[89.   56.34 76.   89.   98.  ]
float64


In [8]:
import numpy as np
scores_1 = [[34,56,23,89],[11,45,76,34]]
second_arr = np.array(scores_1)
print(second_arr)
print(second_arr.ndim)
print(second_arr.shape)
print(second_arr.dtype)

[[34 56 23 89]
 [11 45 76 34]]
2
(2, 4)
int64


In [13]:
import numpy as np
x = np.zeros(5)
print(x)
y= np.ones(10)
print(y)
arange_arr= np.arange(15)
print(arrange_arr)
eye_box = np.eye(6) #identical array
print(eye_box)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [15]:
import numpy as np
new_arr = np.arange(12)
print(new_arr)
print(new_arr[5])
print(new_arr[4:9])
new_arr[4:9] = 99

print(new_arr)
modi_arr = new_arr[4:9]
modi_arr[1] = 123456
print(new_arr)
print(modi_arr[:])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5
[4 5 6 7 8]
[ 0  1  2  3 99 99 99 99 99  9 10 11]
[     0      1      2      3     99 123456     99     99     99      9
     10     11]
[    99 123456     99     99     99]


In [28]:
import numpy as np
matrix_arr = np.array([[3,4,5],[6,7,8],[9,5,1]])
print(matrix_arr)
print(matrix_arr[1])
print(matrix_arr[0][2])

print(matrix_arr[0:2,0:2])
print(matrix_arr[2:,:])
print(matrix_arr[:,:2])

print(matrix_arr[1,:2])

[[3 4 5]
 [6 7 8]
 [9 5 1]]
[6 7 8]
5
[[3 4]
 [6 7]]
[[9 5 1]]
[[3 4]
 [6 7]
 [9 5]]
[6 7]


In [31]:
import numpy as np
thie = np.random.randn(5,5)
print(thie)
print(thie.mean())
print(np.mean(thie))
print(thie.sum())

[[ 0.32878964  0.36246352  0.35346538 -0.18019016 -2.32579533]
 [ 0.36407489  0.55091471  1.50225416 -0.90083361  1.99201634]
 [-0.11191946 -0.4655933   0.55263097 -0.74334257  0.3587802 ]
 [-1.67908511  1.92402353 -0.67598847  0.64398372 -0.08788437]
 [ 0.64541026 -1.49560285  0.29868152 -0.98033698  0.56310898]]
0.03176102543305793
0.03176102543305793
0.7940256358264481


In [41]:
import numpy as np
jp = np.arange(12).reshape(4,3)
print("The arrays are {}".format(jp))
print("The sum of row are ".format(np.sum(jp,axis=1)))

print(jp.sum(1))
lp = np.random.randn(8)
print(lp)
lp.sort()
print(lp)

The arrays are [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The sum of row are 
[ 3 12 21 30]
[-1.83276182 -1.74390328  0.34130515  0.85228971 -0.04867196  2.27031704
 -0.36620048 -1.76207639]
[-1.83276182 -1.76207639 -1.74390328 -0.36620048 -0.04867196  0.34130515
  0.85228971  2.27031704]
